texte=input("donner un mots :")
print(texte)
print("longueur :",len(texte))
print("version en majuscules : ",texte.upper())
print("version en minuscules:", texte.lower())
print("inversion :",texte[::-1])
print("En Python, une chaîne ne peut PAS être modifiée directement.")
print("Quand on applique upper(), lower(), replace(), etc., Python crée une NOUVELLE chaîne.")
print("Ainsi, 'texte' reste toujours la version originale.")